name: Server Tests

on:
  pull_request:
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: flake8 src/ tests/
      - run: pylint src/
      - run: mypy src/
      - run: pytest -v
